# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "@datadrivers/cc-ICAS"
    labels:
      - "gh-actions"
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      # group minor/patch updates for github actions
      github-actions:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: "terraform"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "@datadrivers/cc-ICAS"
    labels:
      - "terraform"
    commit-message:
      prefix: "chore"
      include: "scope"
