name: "Run Terraform via Terragrunt"
description: "This action setup, caches and runs terraform via terragrunt including ssh-agent."

author: Datadrivers GmbH

branding:
  icon: "terminal"
  color: "blue"

inputs:
  terraform-version:
    description: "terraform version to setup. A version is required to install terraform binarys"
    required: false
    default: "disabled"
  terraform-plan-filename:
    description: "name for terraform plan files, which are used as input to generate plan json files as input for pr-commenter action"
    required: false
    default: "terraform.tfplan"
  enable-terraform-change-pr-commenter:
    description: "toggle to add pr comment for terraform-plan-filename files. Requires pre-generated terraform.tfplan file."
    required: false
    default: "false"
  include-plan-job-summary:
    description: "If true, add the results of the plan to the workflow job summary."
    required: false
    default: "true"
  terragrunt-version:
    description: "terragrunt version to setup. A version is required to install terragrunt binarys"
    required: false
    default: "disabled"
  terragrunt-working-directory:
    description: "working-directory for github step to run terragrunt/terraform command"
    required: false
    default: "."
  commands:
    description: "terraform execution line. For multiple commands use | multi line syntax"
    required: true
  use-aws-auth:
    description: "Toggle to log in to aws"
    required: false
    default: "false"
  aws-region:
    description: "AWS Region for Login"
    required: false
    default: "eu-central-1"
  aws-role-to-assume:
    description: "AWS IAM Role for github action to access aws api"
    required: true
  aws-role-duration-seconds:
    description: "AWS session time"
    required: false
    default: "1800"
  use-gcloud-auth:
    description: "Toggle to log in via gcloud to aws"
    required: false
    default: "false"
  gcp-workload-identity-provider:
    description: |-
      The full identifier of the Workload Identity Provider, including the
      project number, pool name, and provider name. If provided, this must be
      the full identifier which includes all parts, for example:
      "projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider".
      This is required if "use-gcloud-auth" is true.
    required: false
    default: ""
  gcp-service-account-email:
    description: |-
      Email address or unique identifier of the Google Cloud service account for
      which to generate credentials. This is required if
      "workload_identity_provider" is specified and "use-gcloud-auth" is true.
    required: false
    default: ""
  gcp-project-id:
    description: |-
      ID of the default project to use for future API calls and invocations. This is required if
      "use-gcloud-auth" is true.
    required: false
  terragrunt-download:
    description: "path to terragrunt cache dir storage"
    required: false
    default: "$HOME/.terragrunt-cache/"
  skip-caches:
    description: "Toggle to skip caches"
    required: false
    default: "false"
  use-ssh-agent:
    description: "Toggle to setup ssh agent with private key. Requires github action secret passed to `ssh-private-key`"
    required: false
    default: "false"
  ssh-private-key:
    description: "Content of secret passed in here`"
    required: false
    default: ""
  enable-debug:
    description: "Add debug output to steps"
    required: false
    default: "false"
  github-token:
    description: 'Github token to use for getting latest release'
    required: false
  use-automatic-binary-detection:
    description: 'This action automatically detects which binary (terraform XOR terragrunt) to use. It does this by checking if terragrunt.hcl is present. If you set this to false terraform will be used'
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    # Setup terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      if: inputs.terraform-version != 'disabled'
      with:
        terraform_version: ${{ inputs.terraform-version }}
        terraform_wrapper: false
    - name: Terragrunt Binary Installer Action
      uses: autero1/action-terragrunt@v3.0.1
      if: inputs.terragrunt-version != 'disabled'
      with:
        terragrunt_version: ${{ inputs.terragrunt-version }}
        token: ${{ inputs.github-token}}
    - name: Config caches
      if: inputs.skip-caches == 'false'
      env:
        INPUT_TERRAGRUNT_DOWNLOAD: ${{ inputs.terragrunt-download }}
      shell: bash
      run: |
        TF_PLUGIN_CACHE_DIR="$HOME/.terraform.d/plugin-cache"
        echo "TF_PLUGIN_CACHE_DIR=$TF_PLUGIN_CACHE_DIR" >> $GITHUB_ENV
        mkdir --parents $TF_PLUGIN_CACHE_DIR
        TERRAGRUNT_DOWNLOAD=${INPUT_TERRAGRUNT_DOWNLOAD//\$HOME/$HOME} # make sure $HOME is expanded
        echo "TERRAGRUNT_DOWNLOAD=$TERRAGRUNT_DOWNLOAD" >> $GITHUB_ENV
        mkdir --parents $TERRAGRUNT_DOWNLOAD
        # clean up to make sure self-hosted runner dirs are clean
        shopt -s dotglob
        cd "${TERRAGRUNT_DOWNLOAD:?}" && rm -rf *
    - name: Cache Terraform
      if: inputs.skip-caches == 'false'
      uses: actions/cache@v4
      with:
        path: |
          ~/.terraform.d/plugin-cache
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
    - name: Cache Terragrunt
      if: inputs.skip-caches == 'false'
      uses: actions/cache@v4
      with:
        path: |
          ${{ env.TERRAGRUNT_DOWNLOAD }}
        key: ${{ runner.os }}-${{ env.TERRAGRUNT_DOWNLOAD }}-${{ hashFiles('**/project.hcl', '**/.terraform.lock.hcl') }}
    - id: "gcloud-auth"
      if: inputs.use-gcloud-auth == 'true'
      name: "Authenticate to GCP"
      uses: "google-github-actions/auth@v2"
      with:
        project_id: ${{ inputs.gcp-project-id }}
        workload_identity_provider: ${{ inputs.gcp-workload-identity-provider }}
        service_account: ${{ inputs.gcp-service-account-email }}
    - id: "aws-auth"
      if: inputs.use-aws-auth == 'true'
      name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.aws-role-to-assume }}
        role-duration-seconds: ${{ inputs.aws-role-duration-seconds }}
    - name: Setup SSH agent
      if: inputs.use-ssh-agent == 'true'
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ inputs.ssh-private-key }}
    - name: Run Terraform
      shell: bash
      working-directory: ${{ inputs.terragrunt-working-directory }}
      run: ${{ inputs.commands }}
    - name: Convert terraform plan files to json
      if: inputs.enable-terraform-change-pr-commenter == 'true'
      env:
        INPUT_TERRAFORM_PLAN_FILENAME: ${{ inputs.terraform-plan-filename }}
        INPUT_USE_AUTOMATIC_BINARY_DETECTION: ${{ inputs.use-automatic-binary-detection }}
        INPUT_ENABLE_DEBUG: ${{ inputs.enable-debug }}
      shell: bash
      id: tf-planfiles
      run: |
        echo "::group::convert terraform plan files to json"
        [[ "$ACT" == "true" ]] && apt-get update && apt-get install parallel -y # on act runner parallel is missing
        set -e
        [[ "${INPUT_ENABLE_DEBUG}" == "true" ]] && set -x
        planfiles_json=()
        tf_convert_plan_to_json(){
          [[ "${INPUT_ENABLE_DEBUG}" == "true" ]] && set -x
          exec 3>&1
          exec 1>&2
          set -e
          local planfile=$1
          planfile_name=$(echo ${planfile##*/})
          planfile_path=$(dirname $planfile)
          terraform_bin="terraform"
          tfplan_json=$(readlink -f "${planfile_path}/tfplan.json")
          cd "${planfile_path}"
          [[ "${INPUT_USE_AUTOMATIC_BINARY_DETECTION}" == "true" ]] && test -s terragrunt.hcl && terraform_bin="terragrunt" || true
          $terraform_bin show -no-color -json "${planfile_name}" > "${tfplan_json}"
          echo ${tfplan_json} >&3
          cd - &>/dev/null
        };
        export -f tf_convert_plan_to_json
        mapfile -t planfiles_json < <( find . -type f -name ${INPUT_TERRAFORM_PLAN_FILENAME} | parallel 'tf_convert_plan_to_json {}' )
        content=$(printf "%s\n" "${planfiles_json[@]}")
        if [[ -n "${content}" ]]; then
          delimiter="$(openssl rand -hex 8)"
          echo "terraform_planfiles_json<<${delimiter}" >> "${GITHUB_OUTPUT}"
          echo "${content}" >> "${GITHUB_OUTPUT}"
          echo "${delimiter}" >> "${GITHUB_OUTPUT}"
        fi
        echo "::endgroup::"
    - name: Add PR comment for terraform plan changes
      if: inputs.enable-terraform-change-pr-commenter == 'true' && endsWith( steps.tf-planfiles.outputs.terraform_planfiles_json , '.json' )
      uses: liatrio/terraform-change-pr-commenter@v1.4.5
      continue-on-error: true
      with:
        include-plan-job-summary: ${{ inputs.include-plan-job-summary }}
        json-file: |
          ${{ steps.tf-planfiles.outputs.terraform_planfiles_json }}
